# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ComputePlayerTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(279, 300)
        Form.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.playerDisplay_groupBox = QtWidgets.QGroupBox(Form)
        self.playerDisplay_groupBox.setAutoFillBackground(False)
        self.playerDisplay_groupBox.setObjectName("playerDisplay_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.playerDisplay_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.playerDisplay_tableWidget = QtWidgets.QTableWidget(self.playerDisplay_groupBox)
        self.playerDisplay_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playerDisplay_tableWidget.setAlternatingRowColors(False)
        self.playerDisplay_tableWidget.setRowCount(0)
        self.playerDisplay_tableWidget.setColumnCount(2)
        self.playerDisplay_tableWidget.setObjectName("playerDisplay_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.playerDisplay_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playerDisplay_tableWidget.setHorizontalHeaderItem(1, item)
        self.playerDisplay_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.playerDisplay_tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_pushButton = QtWidgets.QPushButton(self.playerDisplay_groupBox)
        self.load_pushButton.setObjectName("load_pushButton")
        self.horizontalLayout.addWidget(self.load_pushButton)
        self.editPlayers_pushButton = QtWidgets.QPushButton(self.playerDisplay_groupBox)
        self.editPlayers_pushButton.setObjectName("editPlayers_pushButton")
        self.horizontalLayout.addWidget(self.editPlayers_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(self.playerDisplay_groupBox)
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout.addWidget(self.save_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.playerDisplay_groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playerDisplay_groupBox.setTitle(_translate("Form", "Player Input"))
        item = self.playerDisplay_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Player"))
        item = self.playerDisplay_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Average Elo"))
        self.load_pushButton.setText(_translate("Form", "Load"))
        self.editPlayers_pushButton.setText(_translate("Form", "Edit Players"))
        self.save_pushButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
