# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ComputeOutput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(342, 233)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.computeOutput_groupBox = QtWidgets.QGroupBox(Form)
        self.computeOutput_groupBox.setObjectName("computeOutput_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.computeOutput_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.computeOutput_plainTextEdit = QtWidgets.QPlainTextEdit(self.computeOutput_groupBox)
        self.computeOutput_plainTextEdit.setObjectName("computeOutput_plainTextEdit")
        self.verticalLayout.addWidget(self.computeOutput_plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveOutput_pushButton = QtWidgets.QPushButton(self.computeOutput_groupBox)
        self.saveOutput_pushButton.setObjectName("saveOutput_pushButton")
        self.horizontalLayout.addWidget(self.saveOutput_pushButton)
        self.copyTeams_pushButton = QtWidgets.QPushButton(self.computeOutput_groupBox)
        self.copyTeams_pushButton.setObjectName("copyTeams_pushButton")
        self.horizontalLayout.addWidget(self.copyTeams_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.computeOutput_groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.computeOutput_groupBox.setTitle(_translate("Form", "Compute Output"))
        self.saveOutput_pushButton.setText(_translate("Form", "Save Output"))
        self.copyTeams_pushButton.setText(_translate("Form", "Copy Teams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
