# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ComputeControls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 178)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.computeControls_groupBox = QtWidgets.QGroupBox(Form)
        self.computeControls_groupBox.setObjectName("computeControls_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.computeControls_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.computeMethod_label = QtWidgets.QLabel(self.computeControls_groupBox)
        self.computeMethod_label.setObjectName("computeMethod_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.computeMethod_label)
        self.computeMethod_comboBox = QtWidgets.QComboBox(self.computeControls_groupBox)
        self.computeMethod_comboBox.setObjectName("computeMethod_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.computeMethod_comboBox)
        self.teamSize_label = QtWidgets.QLabel(self.computeControls_groupBox)
        self.teamSize_label.setObjectName("teamSize_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.teamSize_label)
        self.teamSize_spinBox = QtWidgets.QSpinBox(self.computeControls_groupBox)
        self.teamSize_spinBox.setReadOnly(False)
        self.teamSize_spinBox.setMinimum(1)
        self.teamSize_spinBox.setMaximum(1)
        self.teamSize_spinBox.setProperty("value", 1)
        self.teamSize_spinBox.setObjectName("teamSize_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.teamSize_spinBox)
        self.compute_pushButton = QtWidgets.QPushButton(self.computeControls_groupBox)
        self.compute_pushButton.setObjectName("compute_pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.compute_pushButton)
        self.compute_progressBar = QtWidgets.QProgressBar(self.computeControls_groupBox)
        self.compute_progressBar.setAutoFillBackground(False)
        self.compute_progressBar.setProperty("value", 25)
        self.compute_progressBar.setTextVisible(True)
        self.compute_progressBar.setInvertedAppearance(False)
        self.compute_progressBar.setObjectName("compute_progressBar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.compute_progressBar)
        self.compute_info_label = QtWidgets.QLabel(self.computeControls_groupBox)
        self.compute_info_label.setObjectName("compute_info_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.compute_info_label)
        self.gridLayout.addWidget(self.computeControls_groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.computeControls_groupBox.setTitle(_translate("Form", "Compute Controls"))
        self.computeMethod_label.setText(_translate("Form", "Method"))
        self.teamSize_label.setText(_translate("Form", "Team Size"))
        self.compute_pushButton.setText(_translate("Form", "Compute!"))
        self.compute_info_label.setText(_translate("Form", "Total number of team variants:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
