# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\editTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editTable_Dialog(object):
    def setupUi(self, editTable_Dialog):
        editTable_Dialog.setObjectName("editTable_Dialog")
        editTable_Dialog.resize(575, 514)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(editTable_Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(editTable_Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(editTable_Dialog)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clearTable_pushButton = QtWidgets.QPushButton(editTable_Dialog)
        self.clearTable_pushButton.setObjectName("clearTable_pushButton")
        self.verticalLayout.addWidget(self.clearTable_pushButton)
        self.addRow_pushButton = QtWidgets.QPushButton(editTable_Dialog)
        self.addRow_pushButton.setObjectName("addRow_pushButton")
        self.verticalLayout.addWidget(self.addRow_pushButton)
        self.deleteRow_pushButton_2 = QtWidgets.QPushButton(editTable_Dialog)
        self.deleteRow_pushButton_2.setObjectName("deleteRow_pushButton_2")
        self.verticalLayout.addWidget(self.deleteRow_pushButton_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(editTable_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(editTable_Dialog)
        self.buttonBox.accepted.connect(editTable_Dialog.accept)
        self.buttonBox.rejected.connect(editTable_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(editTable_Dialog)

    def retranslateUi(self, editTable_Dialog):
        _translate = QtCore.QCoreApplication.translate
        editTable_Dialog.setWindowTitle(_translate("editTable_Dialog", "Dialog"))
        self.label.setText(_translate("editTable_Dialog", "Input a precalculated average elo into the Elo/Elos column or a set of Elos from which the average will be calculated."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("editTable_Dialog", "Player"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("editTable_Dialog", "Elo/Elos"))
        self.clearTable_pushButton.setText(_translate("editTable_Dialog", "Clear Table"))
        self.addRow_pushButton.setText(_translate("editTable_Dialog", "Add Row"))
        self.deleteRow_pushButton_2.setText(_translate("editTable_Dialog", "Delete Row"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editTable_Dialog = QtWidgets.QDialog()
    ui = Ui_editTable_Dialog()
    ui.setupUi(editTable_Dialog)
    editTable_Dialog.show()
    sys.exit(app.exec_())
